### ISSUE TITLE
Some prolems in run.bat at balana-samples

### ISSUE THREAD

**Issue by frebern** [wso2/balana#67]
Hello, I want to run kmarket-trading-sample, but I meet a problem.

![image](https://cloud.githubusercontent.com/assets/6694664/22773442/8df0b866-eee5-11e6-8014-f10228229fdb.png)
"오류: 기본 클래스 ~~~(를) 찾거나 로드할 수 없습니다." means "Error: Class not Found".
I thought, there is could be some errors in the bat script, so I debugged. 

![image](https://cloud.githubusercontent.com/assets/6694664/22773231/4c89fc94-eee4-11e6-9293-d4848b4d14c7.png)
(I inserted some debug echo)

I don't know 'bat' script, but I noticed BALANA_PATH dosen't set correctly.
I think, some errors or bugs in the script.
Could you fix bat script?

Thanks

**Comment by bergerst** [comment]
You're lucky since I noticed this a month ago but I wanted to wait until my other pull requests were accepted before creating this one.

As a quick solution go to https://github.com/bergerst/balana/tree/samples-run-bat-corrections/modules/balana-samples and download the 4 bat files with the corrections from my fork.

**Comment by frebern** [comment]
![image](https://cloud.githubusercontent.com/assets/6694664/22774525/e0fc78d8-eeea-11e6-8b5a-3734391f7aba.png)

Thanks for your help!! Thank you!

**Comment by bergerst** [comment]
@Can you please reopen the issue? My changes have not been merged yet so other users could encounter the same problem.

Once my pull request gets accepted, it will automatically close this issue.

**Comment by frebern** [comment]
Ok. I reopened it
